#' DuckDB resource helpers for the E3 PROTAC Shiny app.
#'
#' These helpers query the source-first E3 PROTAC DuckDB resource generated by
#' the source-to-Parquet pipeline. They are deliberately generic: the inherited
#' data are still being audited, so the app should expose the available Parquet
#' views safely without assuming a final biological schema too early.

#' Check whether a DuckDB path points to an existing database file.
#'
#' @param duckdb_path Path to a DuckDB database.
#' @return TRUE when the file exists and is not a directory.
resource_database_available <- function(duckdb_path) {
  if (is.list(duckdb_path)) {
    return(resource_source_available(duckdb_path))
  }
  !is.null(duckdb_path) &&
    length(duckdb_path) == 1L &&
    !is.na(duckdb_path) &&
    nzchar(duckdb_path) &&
    file.exists(duckdb_path) &&
    !dir.exists(duckdb_path)
}

#' Attach a DuckDB resource database.
#'
#' @param duckdb_path Path to the DuckDB database.
#' @param alias Alias used for the attached database.
#' @return Sanitised alias.
attach_resource_duckdb <- function(duckdb_path, alias = "e3_resource") {
  if (is.list(duckdb_path)) {
    return(initialise_resource_source(duckdb_path, alias = alias))
  }
  if (!resource_database_available(duckdb_path)) {
    stop(
      paste0(
        "E3 resource DuckDB database was not found: ", duckdb_path,
        "\nSet E3_RESOURCE_DUCKDB or pass --resource_duckdb_path."
      ),
      call. = FALSE
    )
  }

  safe_alias <- sanitise_duckdb_alias(alias = alias)
  safe_path <- escape_sql_literal(normalizePath(duckdb_path, mustWork = TRUE))

  try(duckplyr::db_exec(paste0("DETACH DATABASE IF EXISTS ", safe_alias)), silent = TRUE)
  duckplyr::db_exec(paste0(
    "ATTACH DATABASE '", safe_path, "' AS ", safe_alias, " (READ_ONLY)"
  ))

  safe_alias
}

#' Build a query listing attached-resource views and tables.
#'
#' The source-to-Parquet pipeline creates a `parquet_view_catalog` table. When it
#' is present, that catalog is the clearest source of provenance because it maps
#' each DuckDB view back to its Parquet file. This query returns that table.
#'
#' @param alias Attached database alias.
#' @return SQL query string.
build_resource_relation_catalog_query <- function(alias = "e3_resource") {
  safe_alias <- sanitise_duckdb_alias(alias = alias)

  paste(
    "SELECT relation_name AS view_name, source_parquet AS parquet_file,",
    "'available' AS status, '' AS error, app_section, row_granularity",
    "FROM", paste0(safe_alias, ".main.resource_relation_catalog"),
    "ORDER BY relation_name"
  )
}

#' Build the legacy source-first Parquet view-catalog query.
#'
#' @param alias Attached database alias.
#' @return SQL query string.
build_resource_view_catalog_query <- function(alias = "e3_resource") {
  safe_alias <- sanitise_duckdb_alias(alias = alias)

  paste(
    "SELECT",
    "view_name, parquet_file, status, error",
    "FROM", paste0(safe_alias, ".main.parquet_view_catalog"),
    "ORDER BY view_name"
  )
}

#' Build a fallback query listing DuckDB tables/views.
#'
#' @return SQL query string.
build_resource_information_schema_query <- function(alias = "e3_resource") {
  safe_alias <- escape_sql_literal(sanitise_duckdb_alias(alias))

  paste(
    "SELECT table_name AS view_name, table_type, table_schema",
    "FROM information_schema.tables",
    paste0("WHERE table_catalog = '", safe_alias, "'"),
    "AND table_schema = 'main'",
    "ORDER BY table_name"
  )
}

#' Build a bounded preview query for a resource view.
#'
#' @param view_name DuckDB table or view name.
#' @param max_rows Maximum number of rows to collect.
#' @param alias Attached database alias.
#' @return SQL query string.
build_resource_preview_query <- function(
  view_name,
  max_rows = 1000L,
  alias = "e3_resource"
) {
  safe_alias <- sanitise_duckdb_alias(alias = alias)
  safe_view <- quote_duckdb_identifier(as.character(view_name[[1L]]))
  max_rows <- max(1L, as.integer(max_rows[[1L]]))

  paste(
    "SELECT * FROM",
    paste0(safe_alias, ".main.", safe_view),
    "LIMIT", max_rows
  )
}

#' Build a column-information query for a resource view.
#'
#' @param view_name DuckDB table or view name.
#' @param alias Attached database alias.
#' @return SQL query string.
build_resource_column_query <- function(view_name, alias = "e3_resource") {
  safe_alias <- sanitise_duckdb_alias(alias = alias)
  safe_view_literal <- escape_sql_literal(as.character(view_name[[1L]]))

  paste0(
    "SELECT column_name, data_type AS column_type, is_nullable AS nullable ",
    "FROM information_schema.columns ",
    "WHERE table_catalog = '", safe_alias, "' ",
    "AND table_schema = 'main' ",
    "AND table_name = '", safe_view_literal, "' ",
    "ORDER BY ordinal_position"
  )
}

#' Build a row-count query for a resource view.
#'
#' @param view_name DuckDB table or view name.
#' @param alias Attached database alias.
#' @return SQL query string.
build_resource_row_count_query <- function(view_name, alias = "e3_resource") {
  safe_alias <- sanitise_duckdb_alias(alias = alias)
  safe_view <- quote_duckdb_identifier(as.character(view_name[[1L]]))

  paste("SELECT COUNT(*) AS rows FROM", paste0(safe_alias, ".main.", safe_view))
}

#' Collect a resource query safely.
#'
#' @param duckdb_path Path to the resource DuckDB database.
#' @param query SQL query.
#' @param alias Attached database alias.
#' @return Collected tibble.
collect_resource_query <- function(duckdb_path, query, alias = "e3_resource") {
  if (is.list(duckdb_path)) {
    initialise_resource_source(resource_source = duckdb_path, alias = alias)
  } else {
    attach_resource_duckdb(duckdb_path = duckdb_path, alias = alias)
  }

  duckplyr::read_sql_duckdb(query) |>
    dplyr::collect()
}

#' Collect the source-to-Parquet DuckDB view catalog.
#'
#' @param duckdb_path Path to the resource DuckDB database.
#' @return Tibble with view metadata. Falls back to information_schema.
collect_resource_view_catalog <- function(duckdb_path) {
  tryCatch(
    expr = collect_resource_query(
      duckdb_path = duckdb_path,
      query = build_resource_relation_catalog_query()
    ),
    error = function(error) {
      tryCatch(
        expr = collect_resource_query(
          duckdb_path = duckdb_path,
          query = build_resource_view_catalog_query()
        ),
        error = function(legacy_error) {
          fallback <- collect_resource_query(
            duckdb_path = duckdb_path,
            query = build_resource_information_schema_query(alias = "e3_resource")
          )
          fallback$parquet_file <- NA_character_
          fallback$status <- "available"
          fallback$error <- ""
          fallback
        }
      )
    }
  )
}

#' Collect available resource view names.
#'
#' @param duckdb_path Path to the resource DuckDB database.
#' @return Character vector of view names.
collect_resource_view_names <- function(duckdb_path) {
  catalog <- collect_resource_view_catalog(duckdb_path = duckdb_path)

  if (!"view_name" %in% names(catalog)) {
    return(character())
  }

  names <- as.character(catalog$view_name)
  names <- names[!is.na(names) & nzchar(names)]
  sort(unique(names))
}

#' Collect a bounded preview of a resource view.
#'
#' @param duckdb_path Path to the resource DuckDB database.
#' @param view_name DuckDB view/table name.
#' @param max_rows Maximum rows to collect.
#' @return Tibble preview.
collect_resource_preview <- function(duckdb_path, view_name, max_rows = 1000L) {
  collect_resource_query(
    duckdb_path = duckdb_path,
    query = build_resource_preview_query(
      view_name = view_name,
      max_rows = max_rows
    )
  )
}

#' Collect column metadata for a resource view.
#'
#' @param duckdb_path Path to the resource DuckDB database.
#' @param view_name DuckDB view/table name.
#' @return Tibble of columns.
collect_resource_columns <- function(duckdb_path, view_name) {
  collect_resource_query(
    duckdb_path = duckdb_path,
    query = build_resource_column_query(view_name = view_name)
  )
}

#' Collect row count for one resource view.
#'
#' @param duckdb_path Path to the resource DuckDB database.
#' @param view_name DuckDB view/table name.
#' @return Numeric row count or NA on failure.
collect_resource_row_count <- function(duckdb_path, view_name) {
  result <- collect_resource_query(
    duckdb_path = duckdb_path,
    query = build_resource_row_count_query(view_name = view_name)
  )

  as.numeric(result$rows[[1L]])
}

#' Collapse resource catalog status counts.
#'
#' @param catalog Resource catalog tibble.
#' @return Tibble with status counts.
summarise_resource_catalog_status <- function(catalog) {
  if (is.null(catalog) || nrow(catalog) == 0L || !"status" %in% names(catalog)) {
    return(tibble::tibble(status = character(), n = integer()))
  }

  catalog |>
    dplyr::mutate(status = dplyr::if_else(is.na(.data$status), "unknown", .data$status)) |>
    dplyr::count(.data$status, name = "n") |>
    dplyr::arrange(dplyr::desc(.data$n), .data$status)
}
