name: e3_end_to_end_workflow
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python>=3.11,<3.14
  - pip
  - pyyaml>=6,<7
  - snakemake>=9,<10
  - snakemake-executor-plugin-slurm
  - coverage>=7.6,<8
  - pycodestyle>=2.12,<3
  - pydocstyle>=6.3,<7
  - pytest>=8,<9
