#!/usr/bin/env bash
# Reproduce the complete production E3 Discovery Engine full 1KP+ analysis on
# the University of Dundee Slurm cluster.
#
# This driver records the exact high-level procedure used for the successful
# v0.1.14 run:
#   1. install the checked-out package into the existing Conda environment;
#   2. run the full release checks;
#   3. preflight the inherited 15-source input through the repository's
#      submission wrapper;
#   4. submit the production Slurm job with the tested resource settings;
#   5. wait for completion by default;
#   6. save final sacct accounting and verify workflow_complete.ok plus the
#      formal resource-validation table.
#
# Typical use from the e3_discovery_engine repository root:
#   ./run_e3_discovery_engine_full_onekp_cluster.sh
#
# Submit and return immediately:
#   ./run_e3_discovery_engine_full_onekp_cluster.sh --no-wait
#
# Resume an incomplete run by supplying its original run tag:
#   ./run_e3_discovery_engine_full_onekp_cluster.sh \
#       --run-tag 20260715_100551 --skip-release-checks

set -Eeuo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$({
    cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1
    pwd -P
})"
REPO_ROOT="${SCRIPT_DIR}"

SOURCE_ROOT="/home/pthorpe001/data/2026_E3_protac/SSD_back_up_July_2026/Erin_Butterfield_data"
RESULTS_BASE="/home/pthorpe001/data/2026_E3_protac/e3_discovery_engine_results"
CONDA_ENV="e3_discovery"

ACCOUNT="barton"
PARTITION="general"
CPUS=32
SLURM_MEMORY="256G"
DIAMOND_MEMORY="220G"
WALLTIME="7-00:00:00"
MIN_RESULTS_FREE_GIB=150
MIN_SCRATCH_FREE_GIB=100
SCRATCH_BASE=""
JOB_NAME="e3_onekp_full"
RUN_TAG="$(date +%Y%m%d_%H%M%S)"

RUN_RELEASE_CHECKS="true"
WAIT_FOR_JOB="true"
POLL_SECONDS=60

usage() {
    cat <<'USAGE'
Usage:
  ./run_e3_discovery_engine_full_onekp_cluster.sh [options]

Input and output options:
  --source-root PATH            Erin_Butterfield_data source root.
  --results-base PATH           Persistent production results directory.
  --run-tag TEXT                Stable output identifier/resumption tag.
  --conda-env NAME              Default: e3_discovery.

Slurm and DIAMOND options:
  --account NAME                Default: barton.
  --partition NAME              Default: general.
  --cpus INTEGER                Default: 32.
  --memory VALUE                Slurm memory. Default: 256G.
  --diamond-memory VALUE        DIAMOND limit. Default: 220G.
  --time VALUE                  Default: 7-00:00:00.
  --min-results-free-gib N      Default: 150.
  --min-scratch-free-gib N      Default: 100.
  --scratch-base PATH           Optional fast node-local scratch base.
  --job-name TEXT               Default: e3_onekp_full.

Execution options:
  --skip-release-checks         Skip compile/style/test/coverage checks.
  --no-wait                     Submit the Slurm job and return immediately.
  --poll-seconds INTEGER        Wait-loop interval. Default: 60.
  -h, --help                    Show this help.

A new run tag is generated by default. Supplying an existing incomplete run tag
uses Snakemake restart behaviour. A completed run is never overwritten.
USAGE
}

die() {
    printf 'ERROR: %s\n' "$1" >&2
    exit 2
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --source-root)
            SOURCE_ROOT="${2:?}"
            shift 2
            ;;
        --results-base)
            RESULTS_BASE="${2:?}"
            shift 2
            ;;
        --run-tag)
            RUN_TAG="${2:?}"
            shift 2
            ;;
        --conda-env)
            CONDA_ENV="${2:?}"
            shift 2
            ;;
        --account)
            ACCOUNT="${2:?}"
            shift 2
            ;;
        --partition)
            PARTITION="${2:?}"
            shift 2
            ;;
        --cpus)
            CPUS="${2:?}"
            shift 2
            ;;
        --memory)
            SLURM_MEMORY="${2:?}"
            shift 2
            ;;
        --diamond-memory)
            DIAMOND_MEMORY="${2:?}"
            shift 2
            ;;
        --time)
            WALLTIME="${2:?}"
            shift 2
            ;;
        --min-results-free-gib)
            MIN_RESULTS_FREE_GIB="${2:?}"
            shift 2
            ;;
        --min-scratch-free-gib)
            MIN_SCRATCH_FREE_GIB="${2:?}"
            shift 2
            ;;
        --scratch-base)
            SCRATCH_BASE="${2:?}"
            shift 2
            ;;
        --job-name)
            JOB_NAME="${2:?}"
            shift 2
            ;;
        --skip-release-checks)
            RUN_RELEASE_CHECKS="false"
            shift
            ;;
        --no-wait)
            WAIT_FOR_JOB="false"
            shift
            ;;
        --poll-seconds)
            POLL_SECONDS="${2:?}"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            die "Unknown option: $1"
            ;;
    esac
done

[[ "${RUN_TAG}" =~ ^[A-Za-z0-9._-]+$ ]] || \
    die "--run-tag may contain only letters, digits, '.', '_' and '-'"
for positive_integer in \
    "${CPUS}" \
    "${MIN_RESULTS_FREE_GIB}" \
    "${MIN_SCRATCH_FREE_GIB}" \
    "${POLL_SECONDS}"; do
    [[ "${positive_integer}" =~ ^[1-9][0-9]*$ ]] || \
        die "Expected a positive integer, received: ${positive_integer}"
done

SOURCE_ROOT="$(python -c 'from pathlib import Path; import sys; print(Path(sys.argv[1]).expanduser().resolve())' "${SOURCE_ROOT}")"
RESULTS_BASE="$(python -c 'from pathlib import Path; import sys; print(Path(sys.argv[1]).expanduser().resolve())' "${RESULTS_BASE}")"
REPO_ROOT="$(python -c 'from pathlib import Path; import sys; print(Path(sys.argv[1]).resolve())' "${REPO_ROOT}")"

RUN_ROOT="${RESULTS_BASE}/full_onekp_plus_v0_1_14_${RUN_TAG}"
DRIVER_LOG_DIR="${RESULTS_BASE}/driver_logs/full_onekp_plus_v0_1_14_${RUN_TAG}"
SUBMISSION_LOG="${DRIVER_LOG_DIR}/submission.log"
DRIVER_LOG="${DRIVER_LOG_DIR}/run_e3_discovery_engine_full_onekp.log"

mkdir -p "${DRIVER_LOG_DIR}" "${RESULTS_BASE}"
exec > >(tee -a "${DRIVER_LOG}") 2>&1
trap 'printf "FAILED at line %s: %s\n" "${LINENO}" "${BASH_COMMAND}" >&2' ERR

printf 'Started: %s\n' "$(date --iso-8601=seconds 2>/dev/null || date)"
printf 'Host: %s\n' "$(hostname)"
printf 'Repository: %s\n' "${REPO_ROOT}"
printf 'Source root: %s\n' "${SOURCE_ROOT}"
printf 'Results base: %s\n' "${RESULTS_BASE}"
printf 'Run root: %s\n' "${RUN_ROOT}"
printf 'Run tag: %s\n' "${RUN_TAG}"
printf 'Conda environment: %s\n' "${CONDA_ENV}"
printf 'Resources: %s CPUs; %s Slurm RAM; %s DIAMOND RAM; %s wall time\n' \
    "${CPUS}" "${SLURM_MEMORY}" "${DIAMOND_MEMORY}" "${WALLTIME}"

[[ -f "${REPO_ROOT}/Snakefile" ]] || \
    die "Snakefile is missing from ${REPO_ROOT}"
[[ -x "${REPO_ROOT}/scripts/submit_full_onekp_slurm.sh" ]] || \
    die "Missing executable submit_full_onekp_slurm.sh"
[[ -x "${REPO_ROOT}/scripts/slurm_full_onekp_job.sh" ]] || \
    die "Missing executable slurm_full_onekp_job.sh"
[[ -d "${SOURCE_ROOT}" ]] || die "Missing source root: ${SOURCE_ROOT}"
[[ ! -f "${RUN_ROOT}/workflow_complete.ok" ]] || \
    die "Run is already complete and will not be overwritten: ${RUN_ROOT}"

for required_command in conda sbatch squeue sacct git; do
    command -v "${required_command}" >/dev/null 2>&1 || \
        die "Required command is not available: ${required_command}"
done

printf 'Git commit: '
git -C "${REPO_ROOT}" rev-parse HEAD 2>/dev/null || printf 'unknown\n'
printf 'Git status:\n'
git -C "${REPO_ROOT}" status --short 2>/dev/null || true

conda run \
    --no-capture-output \
    -n "${CONDA_ENV}" \
    python -m pip install --no-deps --editable "${REPO_ROOT}"

if [[ "${RUN_RELEASE_CHECKS}" == "true" ]]; then
    conda run \
        --no-capture-output \
        -n "${CONDA_ENV}" \
        bash "${REPO_ROOT}/scripts/run_release_checks.sh"
fi

submit_command=(
    "${REPO_ROOT}/scripts/submit_full_onekp_slurm.sh"
    --source-root "${SOURCE_ROOT}"
    --results-base "${RESULTS_BASE}"
    --account "${ACCOUNT}"
    --partition "${PARTITION}"
    --cpus "${CPUS}"
    --memory "${SLURM_MEMORY}"
    --diamond-memory "${DIAMOND_MEMORY}"
    --time "${WALLTIME}"
    --conda-env "${CONDA_ENV}"
    --min-results-free-gib "${MIN_RESULTS_FREE_GIB}"
    --min-scratch-free-gib "${MIN_SCRATCH_FREE_GIB}"
    --run-tag "${RUN_TAG}"
    --job-name "${JOB_NAME}"
)
[[ -n "${SCRATCH_BASE}" ]] && \
    submit_command+=(--scratch-base "${SCRATCH_BASE}")

printf 'Submission command:'
printf ' %q' "${submit_command[@]}"
printf '\n'
"${submit_command[@]}" | tee "${SUBMISSION_LOG}"

JOB_ID="$(
    awk '/Submitted Slurm job:/ {print $4}' "${SUBMISSION_LOG}" | tail -n 1
)"
[[ "${JOB_ID}" =~ ^[0-9]+$ ]] || \
    die "Could not recover the submitted Slurm job ID"
printf '%s\n' "${JOB_ID}" > "${DRIVER_LOG_DIR}/slurm_job_id.txt"

printf 'Submitted job ID: %s\n' "${JOB_ID}"
printf 'Monitor with: %s --job-id %s\n' \
    "${REPO_ROOT}/scripts/check_full_onekp_slurm.sh" \
    "${JOB_ID}"

if [[ "${WAIT_FOR_JOB}" != "true" ]]; then
    printf 'Job submitted without waiting. Driver log: %s\n' "${DRIVER_LOG}"
    exit 0
fi

while squeue -h -j "${JOB_ID}" 2>/dev/null | grep -q .; do
    printf '%s | job %s still active\n' \
        "$(date --iso-8601=seconds 2>/dev/null || date)" \
        "${JOB_ID}"
    sleep "${POLL_SECONDS}"
done

printf 'Job %s is no longer in squeue. Retrieving final accounting.\n' \
    "${JOB_ID}"

for attempt in 1 2 3 4 5 6; do
    sacct \
        -j "${JOB_ID}" \
        --units=G \
        --parsable2 \
        --format=JobID,JobName,State,Elapsed,TotalCPU,AllocCPUS,ReqMem,MaxRSS,MaxVMSize,ExitCode \
        > "${RUN_ROOT}/slurm_accounting_final.tsv" || true

    if grep -Eq "^${JOB_ID}\|" "${RUN_ROOT}/slurm_accounting_final.tsv"; then
        break
    fi
    sleep 10
done

cat "${RUN_ROOT}/slurm_accounting_final.tsv" || true

JOB_STATE="$(
    sacct -X -j "${JOB_ID}" -n -P --format=State 2>/dev/null \
        | head -n 1 \
        | cut -d '|' -f 1 \
        | sed 's/[[:space:]]//g' \
        | sed 's/+.*$//'
)"

[[ "${JOB_STATE}" == "COMPLETED" ]] || \
    die "Slurm job did not complete successfully; state=${JOB_STATE:-unknown}"
[[ -f "${RUN_ROOT}/workflow_complete.ok" ]] || \
    die "workflow_complete.ok is missing from ${RUN_ROOT}"

VALIDATION_PATH="${RUN_ROOT}/qc/resource_validation.tsv"
[[ -s "${VALIDATION_PATH}" ]] || \
    die "Resource validation table is missing: ${VALIDATION_PATH}"

conda run \
    --no-capture-output \
    -n "${CONDA_ENV}" \
    python - "${VALIDATION_PATH}" <<'PY'
"""Require every completed discovery-engine validation check to pass."""

from __future__ import annotations

import csv
import sys
from pathlib import Path

validation_path = Path(sys.argv[1])
with validation_path.open(encoding="utf-8", newline="") as handle:
    rows = list(csv.DictReader(handle, delimiter="\t"))

if not rows:
    raise SystemExit(f"Validation table is empty: {validation_path}")

status_column = next(
    (name for name in rows[0] if name.lower() == "status"),
    None,
)
if status_column is None:
    raise SystemExit("Validation table has no status column")

failures = [row for row in rows if row[status_column] != "PASS"]
if failures:
    raise SystemExit(f"Discovery-engine validation failures: {failures}")

print(f"Discovery-engine validation passed: {len(rows)} checks")
PY

REVIEW_BUNDLE="${RESULTS_BASE}/review_bundles/full_onekp_plus_v0_1_14_${RUN_TAG}.tar.gz"
[[ -s "${REVIEW_BUNDLE}" ]] || \
    die "Compact review bundle is missing: ${REVIEW_BUNDLE}"

printf '\nFull 1KP+ production workflow completed successfully.\n'
printf 'Run root: %s\n' "${RUN_ROOT}"
printf 'Review bundle: %s\n' "${REVIEW_BUNDLE}"
printf 'Final accounting: %s\n' "${RUN_ROOT}/slurm_accounting_final.tsv"
printf 'Finished: %s\n' "$(date --iso-8601=seconds 2>/dev/null || date)"
